/**
 * Script de importación: INFORME MELAN 2026_58.xlsx → Supabase
 *
 * Generado automáticamente desde el archivo Excel.
 * Total de registros: 39
 *
 * IMPORTANTE: Antes de ejecutar este script, ejecuta primero la migración
 *   supabase/migration_estados_v2.sql (en Supabase SQL Editor)
 *   para que se acepten los estados 'Estudio de Mercado' y 'A Presentar'.
 *
 * Uso (desde la carpeta melan-crm):
 *     node import-2026.mjs
 *
 * El script borra TODOS los procesos existentes y los reemplaza por los
 * contenidos de este archivo.
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';

const envContent = readFileSync('.env.local', 'utf-8');
const getEnvVar = (name) => {
  const m = envContent.match(new RegExp(`^${name}=(.+)$`, 'm'));
  return m ? m[1].trim() : null;
};

const SUPABASE_URL = getEnvVar('NEXT_PUBLIC_SUPABASE_URL');
const SERVICE_ROLE_KEY = getEnvVar('SUPABASE_SERVICE_ROLE_KEY');

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌ Faltan credenciales en .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const procesos = [
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-10",
    "fecha_presentacion": "2026-01-19",
    "mes_publicacion": "ENERO",
    "entidad": "PATRIMONIO NATURAL FONDO PARA LA BIODIVERSIDAD Y AREAS PROTEGIDAS",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "BOLIVAR",
    "municipio_ejecucion": "CARMEN DE BOLIVAR",
    "cuantia_proceso": 32359300.0,
    "objeto_proceso": "COTIZACION IKI CP 001 2026 EQUIPOS TECNOLÓGICOS",
    "categoria": "INSUMOS DE TECNOLOGÍA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION IKI CP 001 2026",
    "correo_entrega": "adquisiciones@patrimonionatural.org.co",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 32359300.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-05",
    "fecha_presentacion": "2026-01-06",
    "mes_publicacion": "ENERO",
    "entidad": "METRO LÍNEA 1 SAS",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 2320500.0,
    "objeto_proceso": "COMODIN TOMACORRIENTE BULL REF: GN-605 100 UNIDADES",
    "categoria": "SUMINISTRO DE FERRETERÍA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION 12694",
    "correo_entrega": "\"Monica Alejandra Castañeda (OPERATION & MAINTENANCE)\" <monica.c@metro1.com.co>",
    "tiempo_ejecucion": "5 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 2320500.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-07",
    "fecha_presentacion": "2026-01-08",
    "mes_publicacion": "ENERO",
    "entidad": "FANTASIAS PLASTICAS DE COLOMBIA LTDA.",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 929390.0,
    "objeto_proceso": "ARCHIVADOR METALICO 4 GAVETAS NEGRO MEDIDAS 130 X 47 X 5",
    "categoria": "SUMINISTRO MOBILIARIO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION 12695",
    "correo_entrega": "\"compras@fantiplas.com\" <compras@fantiplas.com>",
    "tiempo_ejecucion": "5 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 929390.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-18",
    "fecha_presentacion": "2026-01-20",
    "mes_publicacion": "ENERO",
    "entidad": "INGENIERIA DESAROLLO Y CONSULTORIA INDESCO SAS BIC",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 1748468.0,
    "objeto_proceso": "SUMINISTROS DE INSUMOS DE ASEO",
    "categoria": "INSUMOS DE ASEO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION 12852",
    "correo_entrega": "\"Maria Paula Arias Cubides\" <administracion@grupoindesco.com>",
    "tiempo_ejecucion": "4 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 1748468.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-08",
    "fecha_presentacion": "2026-01-20",
    "mes_publicacion": "ENERO",
    "entidad": "SOCIEDAD NACIONAL DE LA CRUZ ROJA COLOMBIANA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 30362612.0,
    "objeto_proceso": "COMPRA DE MOBILIARIO PARA FORTALECIMIENTO - CRE.",
    "categoria": "SUMINISTRO MOBILIARIO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "GLI-005-2026",
    "correo_entrega": "\"Andres Esteban Roldan Vega\" <andres.roldan@cruzrojacolombiana.org>",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 30362612.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-19",
    "fecha_presentacion": "2026-01-21",
    "mes_publicacion": "ENERO",
    "entidad": "SOCIEDAD NACIONAL DE LA CRUZ ROJA COLOMBIANA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 14296660.0,
    "objeto_proceso": "ELEMENTOS CAMPING, ALMOHADA CAMPING COMFORT Y COLCHONETA",
    "categoria": "SUMINISTRO MOBILIARIO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "GLI-005-2026",
    "correo_entrega": "maricela.quejada@cruzrojacolombiana.org <maricela.quejada@cruzrojacolombiana.org>",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 14296660.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-23",
    "fecha_presentacion": "2026-01-23",
    "mes_publicacion": "ENERO",
    "entidad": "METRO LÍNEA 1 SAS",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 7130480.0,
    "objeto_proceso": "ARCHIVADOR METALICO 3 GAVETAS CON DOS LLAVES MEDIDAS 72 CM DE \nALTO X 37 DE FRENTE X 50 DE FONDO ELABORADA EN LAMINA CALIBRE 22 \nPINTURA ELECTROESTATICA AL CALOR DE ALTA TEMPERATUR",
    "categoria": "SUMINISTRO MOBILIARIO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION 12911",
    "correo_entrega": "\"Luisa Fernanda Daza (Administration DEPT.)\" <luisa.d@metro1.com.co>",
    "tiempo_ejecucion": "5 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 7130480.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-27",
    "fecha_presentacion": "2026-01-28",
    "mes_publicacion": "ENERO",
    "entidad": "METRO LÍNEA 1 SAS",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 32210920.0,
    "objeto_proceso": "COMODIN ESCRITORIO DE 120 CM X 60 CM CON PATA H COLOR NEGRO CON \nARCHIVADOR DE 3 CAJONES CON CHAPA Y 2 LLAVES DE COLOR NEGRO DE \nSUPERFICIE DE 25 MM CANTO RIGIDO Y FORMICA ABEDUL \nALTO X 37 DE FRENTE X 50 DE FONDO ELABORADA EN LAMINA CALIBRE 22 \nPINTURA ELECTROESTATICA AL CALOR DE ALTA TEMPERATUR",
    "categoria": "SUMINISTRO MOBILIARIO",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACION 12911",
    "correo_entrega": "\"Luisa Fernanda Daza (Administration DEPT.)\" <luisa.d@metro1.com.co>",
    "tiempo_ejecucion": "5 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 32210920.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-15",
    "fecha_presentacion": "2026-01-28",
    "mes_publicacion": "ENERO",
    "entidad": "CRUZ ROJA ALEMANA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 105672000.0,
    "objeto_proceso": "KIT HIGIENE FAMILIAR",
    "categoria": "SUMINISTRO DE HIGIENE",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "Proyecto ECHO PCR 26-001",
    "correo_entrega": "valentina.rodriguez@germanredcross.de",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 105672000.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-02",
    "fecha_presentacion": "2026-02-10",
    "mes_publicacion": "FEBRERO",
    "entidad": "CRUZ ROJA ALEMANA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 266400000.0,
    "objeto_proceso": "KIT HIGIENE FAMILIAR",
    "categoria": "SUMINISTRO DE HIGIENE",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "Proyecto ECHO PCR 26-009",
    "correo_entrega": "valentina.rodriguez@germanredcross.de",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 266400000.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-01-15",
    "fecha_presentacion": "2026-01-28",
    "mes_publicacion": "ENERO",
    "entidad": "CRUZ ROJA ALEMANA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 478000000.0,
    "objeto_proceso": "KIT MERCADO FAMILIAR",
    "categoria": "SUMINISTRO DE MERCADOS",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "Proyecto ECHO PCR 26-010",
    "correo_entrega": "valentina.rodriguez@germanredcross.de",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 478000000.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-27",
    "fecha_presentacion": "2026-02-03",
    "mes_publicacion": "FEBRERO",
    "entidad": "DEPARTAMENTO ADMINISTRATIVO DE LA FUNCIÓN PÚBLICA ENTIDAD",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 19931000.0,
    "objeto_proceso": "ADQUISICIÓN DE LA PAPELERÍA, UTILES DE ESCRITORIO Y OFICINA PARA EL USO DE LAS DEPENDENCIAS DE LA FUNCIÓN PÚBLICA",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "ESTUDIO DE MERCADO",
    "numero_proceso": "DAFP-SIP-004-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "5 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 19931000.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-09",
    "fecha_presentacion": "2026-02-18",
    "mes_publicacion": "FEBRERO",
    "entidad": "DIRECCION DE BIENESTAR DE LA POLICIA NACIONAL",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 18218596.55,
    "objeto_proceso": "COMPRAVENTA DE ELEMENTOS DE PAPELERÍA, ÚTILES DE OFICINA Y DEMÁS INSUMOS NECESARIOS PARA EL FUNCIONAMIENTO ADMINISTRATIVO DE LOS PUNTOS DE SERVICIO DE LA DIRECCIÓN DE BIENESTAR SOCIAL Y FAMILIA VIGENCIA 2026",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "PN DIBIE MIC 015 2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "30 DÍAS",
    "proponente_ganador": "FORMARCHIVOS Y SUMINISTROS S.A.S.",
    "participa": "SI",
    "valor_ofertado_ganador": 9879272.39,
    "valor_ofertado_sumicorp": 18218596.55,
    "cantidad_participantes": 35,
    "posicion": 8,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-20",
    "fecha_presentacion": "2026-02-25",
    "mes_publicacion": "FEBRERO",
    "entidad": "DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "ATLANTICO",
    "municipio_ejecucion": "BARRANQUILLA",
    "cuantia_proceso": 19931000.0,
    "objeto_proceso": "SUMINISTRO DE INSUMOS Y EQUIPOS DE ASEO Y CAFETERÍA PARA SER DISTRIBUIDOS EN LAS DIFERENTES SEDES DE LA ADMINISTRACIÓN CENTRAL DE LA ALCALDÍA DISTRITAL DE BARRANQUILLA.",
    "categoria": "INSUMOS DE ASEO Y CAFETERIA",
    "tipo_proceso": "ESTUDIO DE MERCADO",
    "numero_proceso": "SIP-018-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "10 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 19931000.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-24",
    "fecha_presentacion": "2026-03-02",
    "mes_publicacion": "MARZO",
    "entidad": "DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "ATLANTICO",
    "municipio_ejecucion": "BARRANQUILLA",
    "cuantia_proceso": 715555.0,
    "objeto_proceso": "SUMINISTRO DE PAPELERÍA, ÚTILES DE OFICINA Y TÓNERES ORIGINALES Y DEMÁS SUMINISTROS BÁSICOS CON DESTINO A LAS DEPENDENCIAS DE LA ALCALDÍA DEL DISTRITO ESPECIAL, INDUSTRIAL Y PORTUARIO DE BARRANQUILLA",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "ESTUDIO DE MERCADO",
    "numero_proceso": "SIP-019-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "10 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 715555.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-26",
    "fecha_presentacion": "2026-03-04",
    "mes_publicacion": "MARZO",
    "entidad": "DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "ATLANTICO",
    "municipio_ejecucion": "BARRANQUILLA",
    "cuantia_proceso": 80325.0,
    "objeto_proceso": "SUMINISTRO DE KITS DE ASEO E INSUMOS DE LAVANDERÍA PARA LOS HABITANTES DE Y EN CALLE CON FACTORES DE RIESGO EN EL CENTRO DE ACOGIDA Y HOGAR DE PASO DEL DISTRITO ESPECIAL, INDUSTRIAL Y PORTUARIO DE BARRANQUILLA.",
    "categoria": "INSUMOS DE ASEO",
    "tipo_proceso": "ESTUDIO DE MERCADO",
    "numero_proceso": "SIP-023-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "3 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 80325.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-04",
    "fecha_presentacion": "2026-03-09",
    "mes_publicacion": "MARZO",
    "entidad": "POLICÍA METROPOLITANA DE MANIZALES",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CALDAS",
    "municipio_ejecucion": "MANIZALES",
    "cuantia_proceso": 136530700.0,
    "objeto_proceso": "SUMINISTRO DE ELEMENTOS DE ASEO Y PRODUCTOS DE LIMPIEZA CON DESTINO A LA POLICÍA METROPOLITANA DE MANIZALES Y SUS UNIDADES ADSCRITAS",
    "categoria": "INSUMOS DE ASEO",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "PN MEMAZ MIC 003 2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "8 MESES",
    "proponente_ganador": "CONVIL SOLUCIONES S.A.S",
    "participa": "SI",
    "valor_ofertado_ganador": 105814205.0,
    "valor_ofertado_sumicorp": 122088500.0,
    "cantidad_participantes": 22,
    "posicion": 6,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-05",
    "fecha_presentacion": "2026-03-11",
    "mes_publicacion": "MARZO",
    "entidad": "ESCUELA DE CADETES DE POLICIA GENERAL FRANCISCO DE PAULA SANTANDER ECSAN",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 30000000.0,
    "objeto_proceso": "ADQUISICIÓN DE ELEMENTOS DE PAPELERÍA, ÚTILES DE ESCRITORIO Y OFICINA PARA LA ESCUELA DE CADETES DE POLICÍA \"GENERAL FRANCISCO DE PAULA SANTANDER",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "PN ECSAN MIC 011 2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "60 DIAS",
    "proponente_ganador": "SUMICORP LTDA",
    "participa": "SI",
    "valor_ofertado_ganador": 319912.0,
    "valor_ofertado_sumicorp": 759393.0,
    "cantidad_participantes": 30,
    "posicion": 15,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-06",
    "fecha_presentacion": "2026-03-11",
    "mes_publicacion": "MARZO",
    "entidad": "SENA REGIONAL CUNDINAMARCA Grupo Administrativo CBA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "MOSQUERA",
    "cuantia_proceso": 151312235.0,
    "objeto_proceso": "ADQUISICIÓN DE MATERIALES DE FORMACIÓN EN EL ÁREA ADMINISTRATIVA, DEL CENTRO DE BIOTECNOLOGÍA AGROPECUARIA.",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-CMC-CBA-001-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "90 DIAS",
    "proponente_ganador": "DIANA MARCELA MARTINEZ LARA",
    "participa": "SI",
    "valor_ofertado_ganador": 101017366.0,
    "valor_ofertado_sumicorp": 109259185.0,
    "cantidad_participantes": 20,
    "posicion": 8,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-09",
    "fecha_presentacion": "2026-03-13",
    "mes_publicacion": "MARZO",
    "entidad": "SENA DISTRITO CAPITAL GRUPO DE APOYO ADMINISTRATIVO - CGI",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 25028426.0,
    "objeto_proceso": "CONTRATAR LA COMPRA DE MATERIALES DE FORMACIÓN DE PAPELERÍA NECESARIOS PARA EL DESARROLLO DE LOS DIFERENTES PROGRAMAS DE FORMACIÓN QUE IMPARTE EL CENTRO DE GESTIÓN INDUSTRIAL.",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-DC-CGI-003-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "GRUPO LOS LAGOS SAS",
    "participa": "SI",
    "valor_ofertado_ganador": 25028426.0,
    "valor_ofertado_sumicorp": 25028426.0,
    "cantidad_participantes": 14,
    "posicion": 7,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-09",
    "fecha_presentacion": "2026-03-13",
    "mes_publicacion": "MARZO",
    "entidad": "SENA REGIONAL BOLIVAR Grupo de Apoyo Administrativo Mixto",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "BOLIVAR",
    "municipio_ejecucion": "CARTAGENA",
    "cuantia_proceso": 35710250.0,
    "objeto_proceso": "CONTRATAR LA COMPRA DE ELEMENTOS PARA EL DESARROLLO DE ACTIVIDADES RELACIONADAS CON EL DEPORTE, LA RECREACIÓN, EL ARTE Y LA CULTURA EN EL MARCO DEL PLAN INTEGRAL DE BIENESTAR AL APRENDIZ DEL CENTRO AGROEMPRESARIAL Y MINERO DEL SENA REGIONAL BOLÍVAR.",
    "categoria": "INSUMOS DEPORTIVOS",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-BLV-CAM-001-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "IMPERIAL SUPPLY SAS",
    "participa": "SI",
    "valor_ofertado_ganador": 22624479.0,
    "valor_ofertado_sumicorp": 33770500.0,
    "cantidad_participantes": 15,
    "posicion": 13,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-09",
    "fecha_presentacion": "2026-03-13",
    "mes_publicacion": "MARZO",
    "entidad": "SENA REGIONAL ATLANTICO",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "ATLANTICO",
    "municipio_ejecucion": "BARRANQUILLA",
    "cuantia_proceso": 84000000.0,
    "objeto_proceso": "CONTRATAR LA ADQUISICIÓN DE MATERIALES NECESARIOS PARA EL DESARROLLO DE LAS ACTIVIDADES DE EXTENSIÓN CAMPESINA CON ENFOQUE AGROECOLÓGICO PARA LOS 12 NÚCLEOS CAMPESINOS, EN EL MARCO DE LA ESTRATEGIA CAMPESENA, DE LA REGIONAL ATLÁNTICO (FASE 1)",
    "categoria": "INSUMOS LUDICOS",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-ATL-0024-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "Micheell Blanco y/o Grupo empresarial e industrial del caribe",
    "participa": "SI",
    "valor_ofertado_ganador": 5456842.0,
    "valor_ofertado_sumicorp": 5721525.0,
    "cantidad_participantes": 13,
    "posicion": 4,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-10",
    "fecha_presentacion": "2026-03-16",
    "mes_publicacion": "MARZO",
    "entidad": "SECRETARIA DISTRITAL DE SEGURIDAD, CONVIVENCIA Y JUSTICIA",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 113663859.0,
    "objeto_proceso": "13331 - ADQUISICIÓN DE ÚTILES DE OFICINA Y RESMAS DE PAPEL PARA EL NORMAL FUNCIONAMIENTO ADMINISTRATIVO DE LA SECRETARÍA DISTRITAL DE SEGURIDAD, CONVIVENCIA Y JUSTICIA DE BOGOTÁ D.C Y LAS SEDES A SU CARGO",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "SCJ-MC-1-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "2 MESES",
    "proponente_ganador": "DISTRICONSUMOS SAS",
    "participa": "SI",
    "valor_ofertado_ganador": 70283295.0,
    "valor_ofertado_sumicorp": 79848880.0,
    "cantidad_participantes": 26,
    "posicion": 7,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-10",
    "fecha_presentacion": "2026-03-16",
    "mes_publicacion": "MARZO",
    "entidad": "SENA DIRECCION GENERAL",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTA",
    "cuantia_proceso": 15903891.0,
    "objeto_proceso": "CONTRATAR LA ADQUISICIÓN DE EPPS ELEMENTOS DE PROTECCIÓN PERSONAL Y DOTACIÓN DE LA BRIGADA PARA CONTRATISTAS Y FUNCIONARIOS DE LA DIRECCIÓN GENERAL DEL SENA",
    "categoria": "INSUMOS DE PROTECCION PERSONAL",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-DG-SG-0003-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "7 MESES",
    "proponente_ganador": "DIGECOL SAS",
    "participa": "SI",
    "valor_ofertado_ganador": 15903891.0,
    "valor_ofertado_sumicorp": 15957451.0,
    "cantidad_participantes": 39,
    "posicion": 4,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-18",
    "fecha_presentacion": "2026-03-25",
    "mes_publicacion": "MARZO",
    "entidad": "SENA REGIONAL CHOCO Grupo de Apoyo Administrativo Mixto",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CHOCÓ",
    "municipio_ejecucion": "QUIBDÓ",
    "cuantia_proceso": 165289176.0,
    "objeto_proceso": "CONTRATAR LA COMPRA DE ELEMENTOS Y UTENSILIOS DE CAFETERÍA PARA EL CRNIB",
    "categoria": "INSUMOS DE CAFETERIA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-CHC-CRNIB-0008-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "ANDROS GRUPO INTEGRAL S.A.S",
    "participa": "SI",
    "valor_ofertado_ganador": 118459760.0,
    "valor_ofertado_sumicorp": 110426350.0,
    "cantidad_participantes": 11,
    "posicion": 2,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-19",
    "fecha_presentacion": "2026-04-06",
    "mes_publicacion": "ABRIL",
    "entidad": "CAJA DE SUELDOS DE RETIRO DE LA POLICIA NACIONAL",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 103377970.0,
    "objeto_proceso": "SUMINISTRO DE PAPEL, ELEMENTOS DE OFICINA Y ARTÍCULOS RELACIONADOS",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "INV007-26",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "9 MESES",
    "proponente_ganador": "FORMARCHIVOS Y SUMINISTROS S.A.S.",
    "participa": "SI",
    "valor_ofertado_ganador": 57912338.794,
    "valor_ofertado_sumicorp": 67195680.5,
    "cantidad_participantes": 14,
    "posicion": 4,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-06",
    "fecha_presentacion": "2026-04-08",
    "mes_publicacion": "ABRIL",
    "entidad": "IMPRENTA NACIONAL DE COLOMBIA",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 35630300.0,
    "objeto_proceso": "CAJAS X-200 Y X-300",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "REGIMEN ESPECIAL",
    "numero_proceso": "INC-SIP-20261790010243",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "3 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 35630300.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-06",
    "fecha_presentacion": "2026-04-10",
    "mes_publicacion": "ABRIL",
    "entidad": "COMANDO AEREO DE COMBATE No. 6",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CAQUETÁ",
    "municipio_ejecucion": "BAHÍA SOLANO",
    "cuantia_proceso": 93611543.0,
    "objeto_proceso": "ADQUISICIÓN DE ELEMENTOS DE ASEO Y PRODUCTOS PARA EL CACOM-6",
    "categoria": "INSUMOS DE ASEO",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "038-00-I-CACOM-6-GRUAL-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "3 MESES",
    "proponente_ganador": "ARIOS COLOMBIA S.A.S",
    "participa": "SI",
    "valor_ofertado_ganador": 62922063.96,
    "valor_ofertado_sumicorp": 71597809.0,
    "cantidad_participantes": 15,
    "posicion": 7,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-06",
    "fecha_presentacion": "2026-04-10",
    "mes_publicacion": "ABRIL",
    "entidad": "SENA REGIONAL CUNDINAMARCA Grupo de Apoyo Administrativo Mixto+",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 172000000.0,
    "objeto_proceso": "CONTRATAR EL SUMINISTRO DE MATERIALES E INSUMOS REQUERIDOS PARA EL DESARROLLO DE ACTIVIDADES EN EL MARCO DE LA ESTRATEGIA DE EXTENSIÓN CAMPESINA, NÚCLEOS CAMPESINOS Y REDES POPULARES ADELANTADAS POR EL SENA REGIONAL CUNDINAMARCA.",
    "categoria": "INSUMOS DE FERRETERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-CMC-DIR-0107-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "5 MESES",
    "proponente_ganador": "MUNDIAL DE SUMINISTROS Y CONTRATOS S.A.S",
    "participa": "SI",
    "valor_ofertado_ganador": 6331659.0,
    "valor_ofertado_sumicorp": 7505117.0,
    "cantidad_participantes": 8,
    "posicion": 5,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-08",
    "fecha_presentacion": "2026-04-20",
    "mes_publicacion": "ABRIL",
    "entidad": "INSTITUTO NACIONAL DE MEDICINA LEGAL Y CIENCIAS FORENSES",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 45000000.0,
    "objeto_proceso": "363 - ADQUISICION DE PAPELERIA UTILES DE OFICINA Y ESCRITORIO DEL INSTITUTO NACIONAL DE MEDICINA LEGAL Y CIENCIAS FORENSES REGIONAL NORTE",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MiC-0007-DRNT-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "15 DÍAS",
    "proponente_ganador": "COMERCIALIZADORA DIANA",
    "participa": "SI",
    "valor_ofertado_ganador": 31496944.0,
    "valor_ofertado_sumicorp": 33789200.0,
    "cantidad_participantes": 13,
    "posicion": 6,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-23",
    "fecha_presentacion": "2026-04-29",
    "mes_publicacion": "ABRIL",
    "entidad": "SENA TOLIMA 1",
    "estado_proceso": "En Evaluación",
    "departamento_ejecucion": "TOLIMA",
    "municipio_ejecucion": "IBAGUÉ",
    "cuantia_proceso": 125570290.0,
    "objeto_proceso": "CONTRATAR LA ADQUISICIÓN DE ELEMENTOS DE PROTECCIÓN PERSONAL (EPP) Y DOTACIÓN REQUERIDA PARA LA BRIGADA DE EMERGENCIAS DEL SERVICIO NACIONAL DE APRENDIZAJE - SENA REGIONAL TOLIMA, EN CUMPLIMIENTO DE LAS DISPOSICIONES VIGENTES EN MATERIA DE SEGURIDAD Y SALUD EN EL TRABAJO, DURANTE LA VIGENCIA 2026",
    "categoria": "INSUMOS DE PROTECCION PERSONAL",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "MC-DRT-1010-347-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "45 DIÁS",
    "proponente_ganador": null,
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 96630500.0,
    "cantidad_participantes": 23,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-23",
    "fecha_presentacion": "2026-04-30",
    "mes_publicacion": "ABRIL",
    "entidad": "UNIDAD ADMINISTRATIVA ESPECIAL DE CATASTRO DISTRITAL",
    "estado_proceso": "En Evaluación",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 23867154.0,
    "objeto_proceso": "SUMINISTRO DE PRODUCTOS DE PAPELERÍA Y ÚTILES DE OFICINA PARA LA UAECD",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "MINIMA CUANTIA",
    "numero_proceso": "UAECD-MC-004-2026",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "3 MESES",
    "proponente_ganador": null,
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 17601190.0,
    "cantidad_participantes": 17,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Público",
    "fuente": "Secop II",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-02-11",
    "fecha_presentacion": "2026-03-13",
    "mes_publicacion": "MARZO",
    "entidad": "SENA VILLETA",
    "estado_proceso": "Estudio de Mercado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "VILLETA",
    "cuantia_proceso": 1314950.0,
    "objeto_proceso": "INSUMO DE EPP",
    "categoria": "INSUMOS DE PROTECCION PERSONAL",
    "tipo_proceso": "ESTUDIO DE MERCADO",
    "numero_proceso": "COTIZACIÓN EPP",
    "correo_entrega": "SECOP II",
    "tiempo_ejecucion": "45 DIÁS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 1314950.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-20",
    "fecha_presentacion": "2026-03-20",
    "mes_publicacion": "MARZO",
    "entidad": "SOCIEDAD COLOMBIANA DE ANESTESIOLOGIA Y REANIMACION SCARE",
    "estado_proceso": "En Evaluación",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 35453075.0,
    "objeto_proceso": "ELEMENTOS DE TECNOLOGÍA",
    "categoria": "INSUMOS DE TECNOLOGÍA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "COTIZACIÓN TECNOLOGÍA",
    "correo_entrega": "\"comprador2@scare.org.co\" <comprador2@scare.org.co>",
    "tiempo_ejecucion": "30 DÍAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 35453075.0,
    "cantidad_participantes": 0,
    "posicion": 0,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-03-18",
    "fecha_presentacion": "2026-04-08",
    "mes_publicacion": "ABRIL",
    "entidad": "MEDICOS DEL MUNDO",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 2700000.0,
    "objeto_proceso": "SUMINISTRO DE INSUMOS DE ASEO, CAFETERÍA Y PAPELERÍA",
    "categoria": "INSUMOS DE ASEO Y CAFETERIA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "26COLBOG004",
    "correo_entrega": "\"Supply MDM Colombia Bogota\" <supply.bogota.colombia@medecinsdumonde.net>",
    "tiempo_ejecucion": "12 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 2700000.0,
    "cantidad_participantes": 2,
    "posicion": 2,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-20",
    "fecha_presentacion": "2026-04-25",
    "mes_publicacion": "ABRIL",
    "entidad": "SOCIEDAD NACIONAL DE LA CRUZ ROJA COLOMBIANA",
    "estado_proceso": "En Evaluación",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 3939515685.0,
    "objeto_proceso": "ELEMENTOS DE EMERGENCIA, RESCATE Y FERRETERÍA",
    "categoria": "INSUMOS DE PROTECCION PERSONAL",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "SNCRC",
    "correo_entrega": "diana.osorio@cruzrojacolombiana.org.",
    "tiempo_ejecucion": "12 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 3939515685.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-10",
    "fecha_presentacion": "2026-05-08",
    "mes_publicacion": "MAYO",
    "entidad": "CÁMARA DE COMERCIO DE BOGOTÁ",
    "estado_proceso": "A Presentar",
    "departamento_ejecucion": "CUNDINAMARCA",
    "municipio_ejecucion": "BOGOTÁ",
    "cuantia_proceso": 823366215.0,
    "objeto_proceso": "SUMINISTRO DE ELEMENTOS DE ASEO Y CAFETERÍA PARA LAS SEDES DE LA CÁMARA DE COMERCIO DE BOGOTÁ – CCB.",
    "categoria": "INSUMOS DE ASEO Y CAFETERIA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "CONVOCATORIA-2542-2026",
    "correo_entrega": "PLATAFORMA",
    "tiempo_ejecucion": "12 MESES",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 823366215.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-14",
    "fecha_presentacion": "2026-04-17",
    "mes_publicacion": "ABRIL",
    "entidad": "ELECTRIFICADORA DE SANTANDER",
    "estado_proceso": "Adjudicado",
    "departamento_ejecucion": "SANTANDER",
    "municipio_ejecucion": "BUCARAMANGA",
    "cuantia_proceso": 44000000.0,
    "objeto_proceso": "PROTECTOR SOLAR FACTOR DE PROTECCION 60,",
    "categoria": "INSUMOS DE PROTECCION PERSONAL",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "CM-2026-00057",
    "correo_entrega": "CM-2026-00057",
    "tiempo_ejecucion": "6 MESES",
    "proponente_ganador": "SUMIPLAN",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 44000000.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  },
  {
    "sector": "Privado",
    "fuente": "Privado",
    "año_publicacion": 2026,
    "fecha_publicacion": "2026-04-14",
    "fecha_presentacion": "2026-04-17",
    "mes_publicacion": "ABRIL",
    "entidad": "CENTRALES ELÉCTRICAS DEL NORTE DE SANTANDER S.A. E.S.P.",
    "estado_proceso": "En Evaluación",
    "departamento_ejecucion": "NORTE DE SANTANDER",
    "municipio_ejecucion": "CÚCUTA",
    "cuantia_proceso": 12160500.0,
    "objeto_proceso": "ELEMENTOS DE PAPELERÍA Y OFICINA",
    "categoria": "INSUMOS DE PAPELERÍA",
    "tipo_proceso": "REGIMEN PRIVADO",
    "numero_proceso": "CM-2026-00013",
    "correo_entrega": "CM-2026-00013",
    "tiempo_ejecucion": "30 DIAS",
    "proponente_ganador": "PRIVADO",
    "participa": "SI",
    "valor_ofertado_ganador": 0.0,
    "valor_ofertado_sumicorp": 12160500.0,
    "cantidad_participantes": 1,
    "posicion": 1,
    "observaciones": null
  }
];

async function main() {
  console.log(`📥 Importando ${procesos.length} procesos a Supabase...`);

  console.log('🗑️  Borrando procesos existentes...');
  const { error: delErr } = await supabase.from('procesos').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (delErr) {
    console.error('❌ Error borrando:', delErr.message);
    process.exit(1);
  }

  const BATCH = 50;
  let inserted = 0;
  for (let i = 0; i < procesos.length; i += BATCH) {
    const chunk = procesos.slice(i, i + BATCH);
    const { error } = await supabase.from('procesos').insert(chunk);
    if (error) {
      console.error(`❌ Error en lote ${i}:`, error.message);
      process.exit(1);
    }
    inserted += chunk.length;
    console.log(`  ✓ ${inserted}/${procesos.length}`);
  }

  console.log(`✅ Importación completa: ${inserted} procesos`);
}

main().catch(err => { console.error(err); process.exit(1); });
